In [5]:
import pandas as pd


data = [1,2,3,4]
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
dtype: int64

In [6]:
series = pd.Series ([1,2,3,4],index= ['a','b','c','d'])
print (series)
type(series)

a    1
b    2
c    3
d    4
dtype: int64

pandas.core.series.Series

In [7]:
data = {'Name': ['Alice','Bob','Charlie'], 'Age': [24,25,29]}
df = pd.DataFrame(data)
print (df)

      Name  Age
0    Alice   24
1      Bob   25
2  Charlie   29

In [6]:
df.shape

(3, 2)

In [ ]:
df.head()

      Name  Age
0    Alice   24
1      Bob   25
2  Charlie   29

In [7]:
df.tail()

      Name  Age
0    Alice   24
1      Bob   25
2  Charlie   29

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
dtypes: int64(1), object(1)
memory usage: 176.0+ bytes

In [9]:
df.describe()

             Age
count   3.000000
mean   26.000000
std     2.645751
min    24.000000
25%    24.500000
50%    25.000000
75%    27.000000
max    29.000000

In [10]:
df.dtypes

Name    object
Age      int64
dtype: object

In [11]:
file_df = pd.read_csv('./test.csv')
file_df2 = pd.read_excel('./users.xlsx')

In [12]:
file_df.head()

,id,name,email,age,city,country,signup_date,is_active
0,1,Alice Johnson,alice.johnson@example.com,24,New York,USA,2024-01-12,True
1,2,Bob Smith,bob.smith@example.com,31,London,UK,2023-11-03,True
2,3,Charlie Lee,charlie.lee@example.com,27,Toronto,Canada,2024-02-18,False
3,4,Diana Patel,diana.patel@example.com,35,Ahmedabad,India,2022-09-25,True
4,5,Eric Müller,eric.mueller@example.com,29,Berlin,Germany,2023-06-14,True

In [13]:
file_df2.head()

,id,name,email,age,city,country,signup_date,is_active
0,1,Alice Johnson,alice.johnson@example.com,24,New York,USA,2024-01-12,True
1,2,Bob Smith,bob.smith@example.com,31,London,UK,2023-11-03,True

In [14]:
#Creating a simple Dataframe 

data = { 'Name': ['Alice','Bob', 'Charlie'], 'Age': [24,27,22], 'City': ['New York', 'Los Angles', 'Chicago']}
df = pd.DataFrame(data, index = ['a','b', 'c'])
print (df)


#loc df.loc [row label, column ]

      Name  Age        City
a    Alice   24    New York
b      Bob   27  Los Angles
c  Charlie   22     Chicago